/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LakshmiPendantRouteImport } from './routes/lakshmi-pendant'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LakshmiPendantRoute = LakshmiPendantRouteImport.update({
  id: '/lakshmi-pendant',
  path: '/lakshmi-pendant',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lakshmi-pendant': typeof LakshmiPendantRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lakshmi-pendant': typeof LakshmiPendantRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lakshmi-pendant': typeof LakshmiPendantRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lakshmi-pendant'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lakshmi-pendant'
  id: '__root__' | '/' | '/lakshmi-pendant'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LakshmiPendantRoute: typeof LakshmiPendantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lakshmi-pendant': {
      id: '/lakshmi-pendant'
      path: '/lakshmi-pendant'
      fullPath: '/lakshmi-pendant'
      preLoaderRoute: typeof LakshmiPendantRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LakshmiPendantRoute: LakshmiPendantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
