/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BridalJewelleryRouteImport } from './routes/bridal-jewellery'
import { Route as LakshmiPendantRouteImport } from './routes/lakshmi-pendant'
import { Route as StoreLocatorRouteImport } from './routes/store-locator'
import { Route as TraditionalJewelleryRouteImport } from './routes/traditional-jewellery'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BridalJewelleryRoute = BridalJewelleryRouteImport.update({
  id: '/bridal-jewellery',
  path: '/bridal-jewellery',
  getParentRoute: () => rootRouteImport,
} as any)
const LakshmiPendantRoute = LakshmiPendantRouteImport.update({
  id: '/lakshmi-pendant',
  path: '/lakshmi-pendant',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreLocatorRoute = StoreLocatorRouteImport.update({
  id: '/store-locator',
  path: '/store-locator',
  getParentRoute: () => rootRouteImport,
} as any)
const TraditionalJewelleryRoute = TraditionalJewelleryRouteImport.update({
  id: '/traditional-jewellery',
  path: '/traditional-jewellery',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bridal-jewellery': typeof BridalJewelleryRoute
  '/lakshmi-pendant': typeof LakshmiPendantRoute
  '/store-locator': typeof StoreLocatorRoute
  '/traditional-jewellery': typeof TraditionalJewelleryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bridal-jewellery': typeof BridalJewelleryRoute
  '/lakshmi-pendant': typeof LakshmiPendantRoute
  '/store-locator': typeof StoreLocatorRoute
  '/traditional-jewellery': typeof TraditionalJewelleryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bridal-jewellery': typeof BridalJewelleryRoute
  '/lakshmi-pendant': typeof LakshmiPendantRoute
  '/store-locator': typeof StoreLocatorRoute
  '/traditional-jewellery': typeof TraditionalJewelleryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bridal-jewellery'
    | '/lakshmi-pendant'
    | '/store-locator'
    | '/traditional-jewellery'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bridal-jewellery'
    | '/lakshmi-pendant'
    | '/store-locator'
    | '/traditional-jewellery'
  id:
    | '__root__'
    | '/'
    | '/bridal-jewellery'
    | '/lakshmi-pendant'
    | '/store-locator'
    | '/traditional-jewellery'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BridalJewelleryRoute: typeof BridalJewelleryRoute
  LakshmiPendantRoute: typeof LakshmiPendantRoute
  StoreLocatorRoute: typeof StoreLocatorRoute
  TraditionalJewelleryRoute: typeof TraditionalJewelleryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridal-jewellery': {
      id: '/bridal-jewellery'
      path: '/bridal-jewellery'
      fullPath: '/bridal-jewellery'
      preLoaderRoute: typeof BridalJewelleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lakshmi-pendant': {
      id: '/lakshmi-pendant'
      path: '/lakshmi-pendant'
      fullPath: '/lakshmi-pendant'
      preLoaderRoute: typeof LakshmiPendantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store-locator': {
      id: '/store-locator'
      path: '/store-locator'
      fullPath: '/store-locator'
      preLoaderRoute: typeof StoreLocatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traditional-jewellery': {
      id: '/traditional-jewellery'
      path: '/traditional-jewellery'
      fullPath: '/traditional-jewellery'
      preLoaderRoute: typeof TraditionalJewelleryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BridalJewelleryRoute: BridalJewelleryRoute,
  LakshmiPendantRoute: LakshmiPendantRoute,
  StoreLocatorRoute: StoreLocatorRoute,
  TraditionalJewelleryRoute: TraditionalJewelleryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
